### PR TITLE
MCS with non-VPC native (routes-based) cluster

### PR DESCRIPTION
**Pull request by lauralorenz**
Adding in to basic recipe with routes based cluster, since it didn't require very much special setup in the end.

I left in the part that demonstrates explicitly that routes-based clusters cannot export Services --  that beefed up the recipe when it was on its own to, but I'm open to cut that if its feels unnecessary here.

### CODE REVIEW

**Comment by lauralorenz** [comment]
cc @komei-nkmt @mark-church

**Comment by boredabdel** [comment]
Thanks Laura, we are having some discussions on how to structure this repo. I will get back to you next week

**Comment by theemadnes** [comment]
totally unrelated to the general content of the PR, but @lauralorenz can plz you update the image ref from `whereami:v1.1.2` to `whereami:v1.2.1`? I'll put in a PR for the other references.

**Comment by boredabdel** [comment]
Hi Laura,

Please have a look at Alex's ask above to update the image tag

One thing we are trying to do with the repo is to keep each recipe as isolated as possible and keep it in one folder. I like your example but the issue i see is that the instructions are in the MCS folder but the manifests are in a separate folder

So i have two suggestions for you:

- Move the route-based-cluster folder under the multi-cluster-service-basic
- Split the route-based-cluster until it's own folder with it's own readme file

One thing i'm a bit confused with is the purpose of the recipe. My understanding is that you want to demonstrate that when you have a route-based clusters along side a VPC Native Cluster, the route-based cluster can access exported Services on the VPC Native one, but not vice-versa? That's why you deploy a ServiceExport on the route Based cluster and demo that even if it's visible in in vpc native ones it's not accessible. 

What i'm missing i guess is a example to demo that you can have a client on the route-based cluster and access an export service on a vpc native cluster. Maybe i'm missing something here

If Yes than few things

**Comment by boredabdel** [comment]
@lauralorenz Did you had a chance to look at my comments ?

**Pull request closed without merging**
