### PR TITLE
Create test for ingress for custom default backend.

### PR DESCRIPTION
**Pull request by sawsa307**
Create test for ingress for custom default backend.

### CODE REVIEW

**Comment by bowei** [comment]
I thought the purpose of the code is to test the YAMLs checked in, not to write more e2e tests?

**Comment by sawsa307** [comment]
> I thought the purpose of the code is to test the YAMLs checked in, not to write more e2e tests?

Oh do you mean we want to see if the yaml

**Comment by sawsa307** [comment]
> I thought the purpose of the code is to test the YAMLs checked in, not to write more e2e tests?

Yes it is getting into a more e2e test format, but we might fail to check many cases if we only check the yaml creates the corresponding objects, so validating traffic would be more a comprehensive check.

**Review by boredabdel — APPROVED** [review]
LGTM

**Pull request closed without merging**
